name: Update Radar Stats
on:
  schedule:
    - cron: '0 5 * * 1' # Tous les lundis à 5h00 du matin
  workflow_dispatch: # Permet de le lancer à la main depuis GitHub

jobs:
  refresh-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API to refresh Vercel Cache
        run: |
          curl -sL https://ftstoulouse.vercel.app/api/data